### ISSUE TITLE
Mobile version has text from edge to edge.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/My-Baby-Spa#4]
On mobile version text goes from edge to edge of the screen. This needs to be fixed with some padding of about `1em`.

**Comment by iliyaM** [comment]
Checked mobile version looks fine.

**Comment by MeanEYE** [comment]
Hardly looks fine.
![image](https://cloud.githubusercontent.com/assets/1911594/25426814/a6ecb77c-2a70-11e7-8bea-a394dd4ce9db.png)
