### ISSUE TITLE
"our videos on youtube" - הסרטונים שלנו בyoutube

### ISSUE THREAD

**Issue by talovdat** [Way2CU/My-Baby-Spa#6]
The URL is going behaind the video window.
Just drag it to the left so the video wont cover it.
![image](https://cloud.githubusercontent.com/assets/26923359/25426016/802572ea-2a76-11e7-812e-ef10a4fb4ff5.png)

**Comment by MeanEYE** [comment]
That's a retarded way to make a link. Shouldn't be done. Instead link content should be fixed.

**Comment by iliyaM** [comment]
this is issue was because some one remove the () in the markdown section of the article. and it broke. 
fixed now.
